#pragma once

#include <cstdint>

#if defined(_WIN32)
#include <winioctl.h>
#endif

namespace oceanaudio
{
// Device interface GUID for the virtual microphone (placeholder – update with
// the GUID generated by the WDK project).
// {B6B8A19A-08D6-48F1-AACD-3164C3DA7F40}
inline constexpr wchar_t kDeviceInterfaceId[] =
    L"{B6B8A19A-08D6-48F1-AACD-3164C3DA7F40}";

// Control device type reserved for the OceanAudio bridge (placeholder; adjust when
// finalising the WDK project).
inline constexpr std::uint32_t kDeviceType = 0x9C40; // FILE_DEVICE_UNKNOWN range

enum class BridgeIoctl : std::uint32_t
{
    QuerySharedBuffer = 0x800, // returns SharedBufferInfo
    SubmitFrames = 0x801,      // accepts BridgeAudioPacket + float payload
};

#if defined(_WIN32)
inline constexpr std::uint32_t BridgeIoctlCode(BridgeIoctl code)
{
    return CTL_CODE(kDeviceType,
                    static_cast<std::uint32_t>(code),
                    METHOD_BUFFERED,
                    FILE_ANY_ACCESS);
}
#endif

struct SharedBufferInfo
{
    std::uint64_t sharedMemoryHandle; // HANDLE value (UMDF) or section pointer
    std::uint32_t channels;
    std::uint32_t sampleRate;
    std::uint32_t frameCapacity;
    std::uint32_t framesPerBlock;
};

struct BridgeAudioPacket
{
    std::uint32_t framesWritten;
    std::uint32_t reserved;
    // Sample data follows this struct (float interleaved).
};
} // namespace oceanaudio

